import type { IconName } from '../../apps/web/src/icons/manifest';
import type { GeneratedIcon } from '../../apps/web/src/icons/types';

export function renderGeneratedModule(
  icons: ReadonlyArray<readonly [IconName, GeneratedIcon]>
): string {
  const serializedIcons = JSON.stringify(Object.fromEntries(icons), null, 2);

  return (
    `// This file is generated by bun run icons:sync and is intentionally gitignored.\n` +
    `import type { IconName } from './manifest';\n` +
    `import type { GeneratedIcon } from './types';\n\n` +
    `export const generatedIcons: Record<IconName, GeneratedIcon> = ${serializedIcons};\n`
  );
}
