import { createHash } from 'node:crypto';
import type { IconName } from '../../apps/web/src/icons/manifest';
import type { GeneratedIcon } from '../../apps/web/src/icons/types';

const GENERATED_NOTICE =
  '// This file is generated by bun run icons:sync and is intentionally gitignored.\n';
const INPUT_FINGERPRINT_PREFIX = '// Licensed icon inputs: sha256:';
const PAYLOAD_FINGERPRINT_PREFIX = '// Licensed icon payload: sha256:';
const GENERATED_IMPORTS =
  "import type { IconName } from './manifest';\n" +
  "import type { GeneratedIcon } from './types';\n\n";
const GENERATED_ASSIGNMENT = 'export const generatedIcons: Record<IconName, GeneratedIcon> = ';
const SHA256_PATTERN = '[a-f0-9]{64}';

function sha256(value: string): string {
  return createHash('sha256').update(value).digest('hex');
}

export function renderGeneratedModule(
  icons: ReadonlyArray<readonly [IconName, GeneratedIcon]>,
  generationFingerprint: string
): string {
  const serializedIcons = JSON.stringify(Object.fromEntries(icons), null, 2);
  const payloadFingerprint = sha256(serializedIcons);

  return (
    GENERATED_NOTICE +
    `${INPUT_FINGERPRINT_PREFIX}${generationFingerprint}\n` +
    `${PAYLOAD_FINGERPRINT_PREFIX}${payloadFingerprint}\n` +
    GENERATED_IMPORTS +
    `${GENERATED_ASSIGNMENT}${serializedIcons};\n`
  );
}

export function isGeneratedModuleContentFresh(
  generatedModule: string,
  expectedGenerationFingerprint: string,
  expectedIconNames: readonly string[]
): boolean {
  const headerPattern = new RegExp(
    `^${GENERATED_NOTICE.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')}` +
      `${INPUT_FINGERPRINT_PREFIX}(${SHA256_PATTERN})\\n` +
      `${PAYLOAD_FINGERPRINT_PREFIX}(${SHA256_PATTERN})\\n`
  );
  const header = generatedModule.match(headerPattern);
  if (!header || header[1] !== expectedGenerationFingerprint) {
    return false;
  }

  const payloadStart = header[0].length + GENERATED_IMPORTS.length + GENERATED_ASSIGNMENT.length;
  if (
    generatedModule.slice(header[0].length, payloadStart) !==
      GENERATED_IMPORTS + GENERATED_ASSIGNMENT ||
    !generatedModule.endsWith(';\n')
  ) {
    return false;
  }

  const serializedIcons = generatedModule.slice(payloadStart, -2);
  if (sha256(serializedIcons) !== header[2]) {
    return false;
  }

  try {
    const icons: unknown = JSON.parse(serializedIcons);
    if (!icons || typeof icons !== 'object' || Array.isArray(icons)) {
      return false;
    }

    const actualIconNames = Object.keys(icons).sort();
    const requiredIconNames = [...expectedIconNames].sort();
    return (
      actualIconNames.length === requiredIconNames.length &&
      actualIconNames.every((name, index) => name === requiredIconNames[index])
    );
  } catch {
    return false;
  }
}
