import { afterEach, describe, expect, test } from 'bun:test';
import { createHash } from 'node:crypto';
import { copyFile, mkdir, mkdtemp, readFile, rm, stat, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { dirname, resolve } from 'node:path';
import { iconManifest } from '../../apps/web/src/icons/manifest';

const ACTIONABLE_CREDENTIAL_MESSAGE =
  'Missing assets credentials: provide ASSETS_S3_READONLY_ACCESS_KEY_ID and ASSETS_S3_READONLY_SECRET_ACCESS_KEY, or ASSETS_S3_ACCESS_KEY_ID and ASSETS_S3_SECRET_ACCESS_KEY';
const repoRoot = resolve(import.meta.dir, '../..');
const fixtureRoots: string[] = [];

type Manifest = Readonly<Record<string, string>>;

function normalizeSource(source: string): string {
  return source.replaceAll('\r\n', '\n');
}

async function generationFingerprint(manifest: Manifest): Promise<string> {
  const generationSources = await Promise.all(
    ['ops/icons/renderGeneratedModule.ts', 'ops/icons/transform.ts'].map(async (sourcePath) => [
      sourcePath,
      normalizeSource(await readFile(resolve(repoRoot, sourcePath), 'utf8')),
    ])
  );
  const inputs = {
    fingerprintVersion: 1,
    generationSources,
    manifest: Object.entries(manifest).sort(([left], [right]) => left.localeCompare(right)),
  };

  return createHash('sha256').update(JSON.stringify(inputs)).digest('hex');
}

function renderManifest(manifest: Manifest): string {
  return `export const iconManifest = ${JSON.stringify(
    manifest,
    null,
    2
  )} as const;\n\nexport type IconName = keyof typeof iconManifest;\n`;
}

function renderGeneratedModule(manifest: Manifest, fingerprint: string): string {
  const icons = Object.fromEntries(
    Object.keys(manifest).map((name) => [
      name,
      {
        attribution: 'Streamline test attribution',
        paths: [{ d: 'M0 0' }],
        viewBox: '0 0 14 14',
      },
    ])
  );
  const payload = JSON.stringify(icons, null, 2);
  const payloadDigest = createHash('sha256').update(payload).digest('hex');

  return (
    '// This file is generated by bun run icons:sync and is intentionally gitignored.\n' +
    `// Licensed icon inputs: sha256:${fingerprint}\n` +
    `// Licensed icon payload: sha256:${payloadDigest}\n` +
    "import type { IconName } from './manifest';\n" +
    "import type { GeneratedIcon } from './types';\n\n" +
    `export const generatedIcons: Record<IconName, GeneratedIcon> = ${payload};\n`
  );
}

async function copySource(relativePath: string, fixtureRoot: string): Promise<void> {
  const source = resolve(repoRoot, relativePath);
  try {
    await stat(source);
  } catch {
    return;
  }

  const destination = resolve(fixtureRoot, relativePath);
  await mkdir(dirname(destination), { recursive: true });
  await copyFile(source, destination);
}

async function createFixture(options: {
  generatedModule?: string;
  manifest?: Manifest;
}): Promise<string> {
  const fixtureRoot = await mkdtemp(resolve(tmpdir(), 'yucp-icons-runner-'));
  fixtureRoots.push(fixtureRoot);
  const manifest = options.manifest ?? iconManifest;

  await Promise.all(
    [
      'ops/run-web-with-icons.ts',
      'ops/icons/generatedModuleFreshness.ts',
      'ops/icons/generationFingerprint.ts',
      'ops/icons/renderGeneratedModule.ts',
      'ops/icons/transform.ts',
      'apps/web/src/icons/types.ts',
    ].map((relativePath) => copySource(relativePath, fixtureRoot))
  );
  await mkdir(resolve(fixtureRoot, 'apps/web/src/icons'), { recursive: true });
  await writeFile(
    resolve(fixtureRoot, 'apps/web/src/icons/manifest.ts'),
    renderManifest(manifest),
    'utf8'
  );
  if (options.generatedModule !== undefined) {
    await writeFile(
      resolve(fixtureRoot, 'apps/web/src/icons/generated.tsx'),
      options.generatedModule,
      'utf8'
    );
  }

  await writeFile(
    resolve(fixtureRoot, 'package.json'),
    JSON.stringify({
      name: 'licensed-icon-runner-fixture',
      private: true,
      scripts: { 'icons:sync': 'bun run ops/test-icon-sync.ts' },
    }),
    'utf8'
  );
  await writeFile(
    resolve(fixtureRoot, 'ops/test-icon-sync.ts'),
    `await Bun.write(new URL('../sync-invoked.txt', import.meta.url), 'invoked');\nthrow new Error(${JSON.stringify(
      ACTIONABLE_CREDENTIAL_MESSAGE
    )});\n`,
    'utf8'
  );
  await writeFile(
    resolve(fixtureRoot, 'ops/test-external-integrations.ts'),
    "await Bun.write(new URL('../command-invoked.txt', import.meta.url), 'invoked');\n",
    'utf8'
  );

  return fixtureRoot;
}

async function runFixture(fixtureRoot: string): Promise<{
  commandInvoked: boolean;
  exitCode: number;
  stderr: string;
  syncInvoked: boolean;
}> {
  const env = { ...process.env };
  for (const key of Object.keys(env)) {
    if (key.startsWith('ASSETS_S3_')) {
      delete env[key];
    }
  }
  const child = Bun.spawn({
    cmd: [
      process.execPath,
      'run',
      resolve(fixtureRoot, 'ops/run-web-with-icons.ts'),
      'external-integrations',
    ],
    cwd: fixtureRoot,
    env,
    stdout: 'pipe',
    stderr: 'pipe',
  });
  const [exitCode, stderr] = await Promise.all([child.exited, new Response(child.stderr).text()]);

  const exists = async (path: string): Promise<boolean> => {
    try {
      await stat(path);
      return true;
    } catch {
      return false;
    }
  };

  return {
    commandInvoked: await exists(resolve(fixtureRoot, 'command-invoked.txt')),
    exitCode,
    stderr,
    syncInvoked: await exists(resolve(fixtureRoot, 'sync-invoked.txt')),
  };
}

afterEach(async () => {
  await Promise.all(
    fixtureRoots.splice(0).map((fixtureRoot) => rm(fixtureRoot, { recursive: true }))
  );
});

describe('licensed icon runner freshness', () => {
  test('reuses a fresh generated module without invoking sync and proceeds to the command', async () => {
    const fingerprint = await generationFingerprint(iconManifest);
    const fixtureRoot = await createFixture({
      generatedModule: renderGeneratedModule(iconManifest, fingerprint),
    });

    const result = await runFixture(fixtureRoot);

    expect(result).toMatchObject({ commandInvoked: true, exitCode: 0, syncInvoked: false });
  });

  test('fails loudly when the generated module and asset credentials are missing', async () => {
    const fixtureRoot = await createFixture({});

    const result = await runFixture(fixtureRoot);

    expect(result.exitCode).not.toBe(0);
    expect(result.syncInvoked).toBe(true);
    expect(result.commandInvoked).toBe(false);
    expect(result.stderr).toContain(ACTIONABLE_CREDENTIAL_MESSAGE);
  });

  test('invokes sync when the manifest changed after generation', async () => {
    const fingerprint = await generationFingerprint(iconManifest);
    const fixtureRoot = await createFixture({
      generatedModule: renderGeneratedModule(iconManifest, fingerprint),
    });
    const changedManifest = { ...iconManifest, renamedCopy: iconManifest.copy };
    await writeFile(
      resolve(fixtureRoot, 'apps/web/src/icons/manifest.ts'),
      renderManifest(changedManifest),
      'utf8'
    );

    const result = await runFixture(fixtureRoot);

    expect(result.syncInvoked).toBe(true);
    expect(result.commandInvoked).toBe(false);
  });

  test('invokes sync when the generated module is corrupt or truncated', async () => {
    const fingerprint = await generationFingerprint(iconManifest);
    const completeModule = renderGeneratedModule(iconManifest, fingerprint);
    const fixtureRoot = await createFixture({
      generatedModule: completeModule.slice(0, Math.floor(completeModule.length / 2)),
    });

    const result = await runFixture(fixtureRoot);

    expect(result.syncInvoked).toBe(true);
    expect(result.commandInvoked).toBe(false);
  });
});
