/**
 * This file is auto-generated. Do not edit this file manually.
 * To regenerate the schema, from your project root:
 *
 *   cd convex/betterAuth
 *   bunx auth@1.7.0-rc.2 generate --output "./schema.ts"
 *
 * To customize the schema, generate to an alternate file and import
 * the table definitions to your schema file. See
 * https://labs.convex.dev/better-auth/features/local-install#adding-custom-indexes.
 */

import { defineSchema, defineTable } from "convex/server";
import { v } from "convex/values";

export const tables = {
  user: defineTable({
    name: v.string(),
    email: v.string(),
    emailVerified: v.boolean(),
    image: v.optional(v.union(v.null(), v.string())),
    createdAt: v.number(),
    updatedAt: v.number(),
    twoFactorEnabled: v.optional(v.union(v.null(), v.boolean())),
    userId: v.optional(v.union(v.null(), v.string())),
  })
    .index("email_name", ["email","name"])
    .index("name", ["name"])
    .index("userId", ["userId"]),
  session: defineTable({
    expiresAt: v.number(),
    token: v.string(),
    createdAt: v.number(),
    updatedAt: v.number(),
    ipAddress: v.optional(v.union(v.null(), v.string())),
    userAgent: v.optional(v.union(v.null(), v.string())),
    userId: v.string(),
  })
    .index("expiresAt", ["expiresAt"])
    .index("expiresAt_userId", ["expiresAt","userId"])
    .index("token", ["token"])
    .index("userId", ["userId"]),
  account: defineTable({
    issuer: v.string(),
    providerAccountId: v.string(),
    providerId: v.string(),
    userId: v.string(),
    accessToken: v.optional(v.union(v.null(), v.string())),
    refreshToken: v.optional(v.union(v.null(), v.string())),
    idToken: v.optional(v.union(v.null(), v.string())),
    accessTokenExpiresAt: v.optional(v.union(v.null(), v.number())),
    refreshTokenExpiresAt: v.optional(v.union(v.null(), v.number())),
    scope: v.optional(v.union(v.null(), v.string())),
    password: v.optional(v.union(v.null(), v.string())),
    createdAt: v.number(),
    updatedAt: v.number(),
  })
    .index("issuer_providerAccountId", ["issuer","providerAccountId"])
    .index("providerId_userId", ["providerId","userId"])
    .index("userId", ["userId"]),
  verification: defineTable({
    identifier: v.string(),
    value: v.string(),
    expiresAt: v.number(),
    createdAt: v.number(),
    updatedAt: v.number(),
  })
    .index("expiresAt", ["expiresAt"])
    .index("identifier", ["identifier"]),
  apikey: defineTable({
    configId: v.string(),
    name: v.optional(v.union(v.null(), v.string())),
    start: v.optional(v.union(v.null(), v.string())),
    referenceId: v.string(),
    prefix: v.optional(v.union(v.null(), v.string())),
    key: v.string(),
    refillInterval: v.optional(v.union(v.null(), v.number())),
    refillAmount: v.optional(v.union(v.null(), v.number())),
    lastRefillAt: v.optional(v.union(v.null(), v.number())),
    enabled: v.optional(v.union(v.null(), v.boolean())),
    rateLimitEnabled: v.optional(v.union(v.null(), v.boolean())),
    rateLimitTimeWindow: v.optional(v.union(v.null(), v.number())),
    rateLimitMax: v.optional(v.union(v.null(), v.number())),
    requestCount: v.optional(v.union(v.null(), v.number())),
    remaining: v.optional(v.union(v.null(), v.number())),
    lastRequest: v.optional(v.union(v.null(), v.number())),
    expiresAt: v.optional(v.union(v.null(), v.number())),
    createdAt: v.number(),
    updatedAt: v.number(),
    permissions: v.optional(v.union(v.null(), v.string())),
    metadata: v.optional(v.union(v.null(), v.string())),
  })
    .index("configId", ["configId"])
    .index("expiresAt", ["expiresAt"])
    .index("referenceId", ["referenceId"]),
  jwks: defineTable({
    publicKey: v.string(),
    privateKey: v.string(),
    createdAt: v.number(),
    expiresAt: v.optional(v.union(v.null(), v.number())),
    alg: v.optional(v.union(v.null(), v.string())),
    crv: v.optional(v.union(v.null(), v.string())),
  }),
  oauthClient: defineTable({
    clientId: v.string(),
    clientSecret: v.optional(v.union(v.null(), v.string())),
    disabled: v.optional(v.union(v.null(), v.boolean())),
    skipConsent: v.optional(v.union(v.null(), v.boolean())),
    enableEndSession: v.optional(v.union(v.null(), v.boolean())),
    subjectType: v.optional(v.union(v.null(), v.string())),
    scopes: v.optional(v.union(v.null(), v.array(v.string()))),
    userId: v.optional(v.union(v.null(), v.string())),
    createdAt: v.optional(v.union(v.null(), v.number())),
    updatedAt: v.optional(v.union(v.null(), v.number())),
    name: v.optional(v.union(v.null(), v.string())),
    uri: v.optional(v.union(v.null(), v.string())),
    icon: v.optional(v.union(v.null(), v.string())),
    contacts: v.optional(v.union(v.null(), v.array(v.string()))),
    tos: v.optional(v.union(v.null(), v.string())),
    policy: v.optional(v.union(v.null(), v.string())),
    softwareId: v.optional(v.union(v.null(), v.string())),
    softwareVersion: v.optional(v.union(v.null(), v.string())),
    softwareStatement: v.optional(v.union(v.null(), v.string())),
    redirectUris: v.array(v.string()),
    postLogoutRedirectUris: v.optional(v.union(v.null(), v.array(v.string()))),
    backchannelLogoutUri: v.optional(v.union(v.null(), v.string())),
    backchannelLogoutSessionRequired: v.optional(v.union(v.null(), v.boolean())),
    tokenEndpointAuthMethod: v.optional(v.union(v.null(), v.string())),
    jwks: v.optional(v.union(v.null(), v.string())),
    jwksUri: v.optional(v.union(v.null(), v.string())),
    grantTypes: v.optional(v.union(v.null(), v.array(v.string()))),
    responseTypes: v.optional(v.union(v.null(), v.array(v.string()))),
    public: v.optional(v.union(v.null(), v.boolean())),
    type: v.optional(v.union(v.null(), v.string())),
    requirePKCE: v.optional(v.union(v.null(), v.boolean())),
    dpopBoundAccessTokens: v.optional(v.union(v.null(), v.boolean())),
    referenceId: v.optional(v.union(v.null(), v.string())),
    metadata: v.optional(v.union(v.null(), v.string())),
  })
    .index("clientId", ["clientId"])
    .index("userId", ["userId"]),
  oauthResource: defineTable({
    identifier: v.string(),
    name: v.string(),
    accessTokenTtl: v.optional(v.union(v.null(), v.number())),
    refreshTokenTtl: v.optional(v.union(v.null(), v.number())),
    signingAlgorithm: v.optional(v.union(v.null(), v.string())),
    signingKeyId: v.optional(v.union(v.null(), v.string())),
    allowedScopes: v.optional(v.union(v.null(), v.array(v.string()))),
    customClaims: v.optional(v.union(v.null(), v.string())),
    dpopBoundAccessTokensRequired: v.optional(v.union(v.null(), v.boolean())),
    disabled: v.optional(v.union(v.null(), v.boolean())),
    createdAt: v.optional(v.union(v.null(), v.number())),
    updatedAt: v.optional(v.union(v.null(), v.number())),
    policyVersion: v.optional(v.union(v.null(), v.number())),
    metadata: v.optional(v.union(v.null(), v.string())),
  })
    .index("identifier", ["identifier"]),
  oauthClientResource: defineTable({
    clientId: v.string(),
    resourceId: v.string(),
    metadata: v.optional(v.union(v.null(), v.string())),
    createdAt: v.optional(v.union(v.null(), v.number())),
  })
    .index("clientId", ["clientId"])
    .index("resourceId", ["resourceId"]),
  oauthRefreshToken: defineTable({
    token: v.string(),
    clientId: v.string(),
    sessionId: v.optional(v.union(v.null(), v.string())),
    userId: v.string(),
    referenceId: v.optional(v.union(v.null(), v.string())),
    authorizationCodeId: v.optional(v.union(v.null(), v.string())),
    resources: v.optional(v.union(v.null(), v.array(v.string()))),
    requestedUserInfoClaims: v.optional(v.union(v.null(), v.array(v.string()))),
    expiresAt: v.optional(v.union(v.null(), v.number())),
    createdAt: v.optional(v.union(v.null(), v.number())),
    revoked: v.optional(v.union(v.null(), v.number())),
    rotatedAt: v.optional(v.union(v.null(), v.number())),
    rotationReplayResponse: v.optional(v.union(v.null(), v.string())),
    rotationReplayExpiresAt: v.optional(v.union(v.null(), v.number())),
    authTime: v.optional(v.union(v.null(), v.number())),
    confirmation: v.optional(v.union(v.null(), v.string())),
    scopes: v.array(v.string()),
  })
    .index("token", ["token"])
    .index("clientId", ["clientId"])
    .index("sessionId", ["sessionId"])
    .index("userId", ["userId"]),
  oauthAccessToken: defineTable({
    token: v.optional(v.union(v.null(), v.string())),
    clientId: v.string(),
    sessionId: v.optional(v.union(v.null(), v.string())),
    userId: v.optional(v.union(v.null(), v.string())),
    referenceId: v.optional(v.union(v.null(), v.string())),
    authorizationCodeId: v.optional(v.union(v.null(), v.string())),
    resources: v.optional(v.union(v.null(), v.array(v.string()))),
    requestedUserInfoClaims: v.optional(v.union(v.null(), v.array(v.string()))),
    refreshId: v.optional(v.union(v.null(), v.string())),
    expiresAt: v.optional(v.union(v.null(), v.number())),
    createdAt: v.optional(v.union(v.null(), v.number())),
    revoked: v.optional(v.union(v.null(), v.number())),
    confirmation: v.optional(v.union(v.null(), v.string())),
    scopes: v.array(v.string()),
  })
    .index("token", ["token"])
    .index("clientId", ["clientId"])
    .index("sessionId", ["sessionId"])
    .index("userId", ["userId"])
    .index("refreshId", ["refreshId"]),
  oauthConsent: defineTable({
    clientId: v.string(),
    userId: v.optional(v.union(v.null(), v.string())),
    referenceId: v.optional(v.union(v.null(), v.string())),
    resources: v.optional(v.union(v.null(), v.array(v.string()))),
    requestedUserInfoClaims: v.optional(v.union(v.null(), v.array(v.string()))),
    scopes: v.array(v.string()),
    createdAt: v.optional(v.union(v.null(), v.number())),
    updatedAt: v.optional(v.union(v.null(), v.number())),
  })
    .index("clientId_userId", ["clientId","userId"])
    .index("userId", ["userId"]),
  oauthClientAssertion: defineTable({
    expiresAt: v.number(),
  }),
  twoFactor: defineTable({
    secret: v.string(),
    backupCodes: v.string(),
    userId: v.string(),
    verified: v.optional(v.union(v.null(), v.boolean())),
    failedVerificationCount: v.optional(v.union(v.null(), v.number())),
    lockedUntil: v.optional(v.union(v.null(), v.number())),
  })
    .index("userId", ["userId"]),
  passkey: defineTable({
    name: v.optional(v.union(v.null(), v.string())),
    publicKey: v.string(),
    userId: v.string(),
    credentialID: v.string(),
    counter: v.number(),
    deviceType: v.string(),
    backedUp: v.boolean(),
    transports: v.optional(v.union(v.null(), v.string())),
    createdAt: v.optional(v.union(v.null(), v.number())),
    aaguid: v.optional(v.union(v.null(), v.string())),
  })
    .index("userId", ["userId"]),
};

const schema = defineSchema(tables);

export default schema;
