export const iconManifest = {
  activity: 'Health/Medical Monitoring/Heart Rate Pulse Graph.svg',
  add: 'Interface Essential/Add Remove Delete/Add 1.svg',
  addCircle: 'Interface Essential/Add Remove Delete/Add Circle.svg',
  alert: 'Interface Essential/Alerts/Warning Circle.svg',
  analytics: 'Business/Marketing Strategy/Statistics Report.svg',
  arrowDown: 'Arrows/Single Line Arrow/Line Arrow Down 1.svg',
  arrowDownLarge: 'Arrows/Big Single Line Arrow/Line Arrow Down Large 1.svg',
  arrowLeft: 'Arrows/Single Line Arrow/Line Arrow Left 1.svg',
  arrowRight: 'Arrows/Single Line Arrow/Line Arrow Right 1.svg',
  arrowUp: 'Arrows/Single Line Arrow/Line Arrow Up 1.svg',
  auditLog: 'Interface Essential/Files Folders/File Document Edit History.svg',
  bell: 'Interface Essential/Alerts/Ringing Bell Notification.svg',
  billing: 'Money Shopping/ATM/Credit Card 1.svg',
  bot: 'Computer Devices/Robot/Ai Chat Bot.svg',
  check: 'Interface Essential/Validation/Check.svg',
  chevronDown: 'Arrows/Thick Arrow/Chevron Arrow Down.svg',
  chevronRight: 'Arrows/Thick Arrow/Chevron Arrow Right.svg',
  chevronUp: 'Arrows/Thick Arrow/Chevron Arrow Up.svg',
  clipboard: 'Interface Essential/Files Folders/Clipboard Text.svg',
  clock: 'Interface Essential/Time/Circle Clock.svg',
  close: 'Interface Essential/Add Remove Delete/Delete 1.svg',
  code: 'Programming/Script/Code Bracket.svg',
  collaboration: 'Interface Essential/User/User Collaborate Group.svg',
  copy: 'Interface Essential/Select Copy/Copy Paste.svg',
  desktop: 'Computer Devices/Computer/Desktop.svg',
  documentation: 'Interface Essential/Contents/Library Books.svg',
  download: 'Interface Essential/Upload Download/Download Tray.svg',
  edit: 'Interface Essential/Edit/Pencil.svg',
  externalLink: 'Interface Essential/Layouts/New Window.svg',
  eye: 'Interface Essential/View/Visible.svg',
  eyeOff: 'Interface Essential/View/Invisible 1.svg',
  file: 'Interface Essential/Files Folders/File.svg',
  fileSearch: 'Interface Essential/Files Folders/File Search.svg',
  filter: 'Interface Essential/Text Formatting/Filter 1.svg',
  globe: 'Map Travel/Map/Globe.svg',
  home: 'Interface Essential/Home/Home 3.svg',
  inbox: 'Mail/Inbox/Inbox.svg',
  info: 'Interface Essential/Alerts/Information Circle.svg',
  integration: 'Programming/Web/Connection Integration System Api.svg',
  key: 'Interface Essential/Login Logout/Key.svg',
  layoutGrid: 'Interface Essential/Layouts/Layout Grid.svg',
  leakTrace: 'Interface Essential/ID/Fingerprint Scan 1.svg',
  license: 'Business/Marketing Strategy/Contracts.svg',
  link: 'Interface Essential/Link Unlink/Link Chain Check Validate.svg',
  lock: 'Interface Essential/Lock Unlock/Encrypted Lock.svg',
  login: 'Interface Essential/Login Logout/Login 1.svg',
  logout: 'Interface Essential/Login Logout/Logout 1.svg',
  mail: 'Mail/Inbox/Mail Notification.svg',
  menu: 'Interface Essential/Setting/Hamburger Menu 2.svg',
  minus: 'Interface Essential/Add Remove Delete/Subtract 1.svg',
  moon: 'Interface Essential/Weather/Angled Moon.svg',
  package: 'Shipping/Box/Package.svg',
  party: 'Entertainment/Party/Party Popper.svg',
  plug: 'Computer Devices/Connection/Plugs.svg',
  privacy: 'Interface Essential/Security/Shield Privacy Policy Check.svg',
  profile: 'Interface Essential/User/User Profile Focus.svg',
  refresh: 'Programming/Browser/Browser Refresh.svg',
  rules: 'Business/Business Office/Task List.svg',
  search: 'Interface Essential/Search/Magnifying Glass.svg',
  settings: 'Interface Essential/Setting/Cog Automation.svg',
  shield: 'Interface Essential/Security/Shield Check.svg',
  shieldAlert: 'Interface Essential/Alerts/Warning Shield.svg',
  star: 'Interface Essential/Trophy Award/Star Badge.svg',
  store: 'Money Shopping/Building Store/Store 1.svg',
  success: 'Interface Essential/Validation/Check Circle.svg',
  sun: 'Interface Essential/Weather/Sun.svg',
  ticket: 'Culture/Tickets/Ticket 1.svg',
  trash: 'Interface Essential/Add Remove Delete/Trash Bin Remove.svg',
  upload: 'Interface Essential/Upload Download/Upload Tray.svg',
  user: 'Interface Essential/User/User Circle Single.svg',
  userKey: 'Interface Essential/User/User Account Passkey.svg',
  users: 'Interface Essential/User/User Group.svg',
  webhook: 'Programming/Web/Webhook.svg',
} as const satisfies Record<string, `${string}.svg`>;

export type IconName = keyof typeof iconManifest;
