/**
 * Live Lore Backstage publish and VPM download acceptance harness.
 *
 * Required environment variables:
 *   YUCP_API_BASE_URL                Running public API base URL, for example https://api.example.com.
 *   YUCP_ACCESS_TOKEN                Better Auth OAuth token with the yucp-public-api audience and products:write scope.
 *   YUCP_BACKSTAGE_REPO_TOKEN        Active buyer repo token entitled to the target catalog product.
 *   YUCP_CATALOG_PRODUCT_ID          Catalog product id used as the release access selector.
 *   YUCP_PACKAGE_ID                  Backstage/VPM package id to publish.
 *   YUCP_PACKAGE_VERSION             New, unpublished version to publish and download.
 *
 * Optional environment variables:
 *   YUCP_SECOND_PACKAGE_VERSION      New, unpublished version for a second modified-ZIP publish and download pass.
 *
 * Optional argument:
 *   --source <path>                  Source ZIP or unitypackage. A small in-memory VPM ZIP is generated by default.
 *
 * Infrastructure prerequisites:
 *   - The public API URL above is reachable and accepts the supplied OAuth token.
 *   - The API-returned TUS sidecar endpoint and loreserver are reachable from this process.
 *   - BACKSTAGE_INGEST_SECRET is shared by the API and sidecar, and all required LORE_* and
 *     Cloudflare Access values are configured for the API, sidecar, and loreserver.
 *   - The repo token's buyer subject is entitled to YUCP_CATALOG_PRODUCT_ID.
 *   - Each configured package version is unused before the run.
 *
 * Run with:
 *   bun run smoke:lore
 *   bun run smoke:lore -- --source ./path/to/package.zip
 */

import { createHash } from 'node:crypto';
import { basename, extname, resolve } from 'node:path';
import { parseArgs } from 'node:util';
import { strToU8, unzipSync, type Zippable, zipSync } from 'fflate';
import { Upload } from 'tus-js-client';
import type {
  PublishBackstagePackageResult,
  PublishBackstageReleaseConfig,
} from './publish-backstage-package';

const BACKSTAGE_INGEST_RESULT_HEADER = 'X-Backstage-Ingest-Result';
const BACKSTAGE_TUS_CHUNK_SIZE = 64 * 1024 * 1024;
const REPO_TOKEN_HEADER = 'X-YUCP-Repo-Token';
const REPOSITORY_PATH = '/v1/backstage/repos/index.json';
const FETCH_TIMEOUT_MS = 60_000;
const LORE_PRESIGNED_URL_PATTERN =
  /^https?:\/\/.+\/v1\/presigned\/[0-9a-f]{32}\/[0-9a-f]{64}-[0-9a-f]{32}\?token=/;
const FIXED_ZIP_MTIME = new Date('1980-01-01T00:00:00.000Z');

type Config = PublishBackstageReleaseConfig & {
  repoToken: string;
  sourcePath?: string;
  secondVersion?: string;
};

type SourceArtifact = {
  bytes: Uint8Array;
  contentType: string;
  deliveryName: string;
};

type UploadAuthorization = {
  tusEndpoint: string;
  uploadToken: string;
  uploadMetadataKey: string;
  maxByteSize: number;
};

type RepositoryManifest = {
  headers: Record<string, string>;
  url: string;
  zipSha256: string;
};

type DownloadedArtifact = {
  bytes: Uint8Array;
  redirectLocation: string;
  sha256: string;
};

function requiredEnv(env: NodeJS.ProcessEnv, name: string): string {
  const value = env[name]?.trim();
  if (!value) {
    throw new Error(
      `Missing required environment variable ${name}. See the file header for setup.`
    );
  }
  return value;
}

function optionalEnv(env: NodeJS.ProcessEnv, name: string): string | undefined {
  const value = env[name]?.trim();
  return value || undefined;
}

function buildApiUrl(apiBaseUrl: string, path: string): string {
  return new URL(path, apiBaseUrl.endsWith('/') ? apiBaseUrl : `${apiBaseUrl}/`).toString();
}

function sha256Hex(bytes: Uint8Array): string {
  return createHash('sha256').update(bytes).digest('hex');
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === 'object' && value !== null && !Array.isArray(value);
}

function getStringHeaders(value: unknown): Record<string, string> {
  if (!isRecord(value)) {
    return {};
  }
  return Object.fromEntries(
    Object.entries(value).filter((entry): entry is [string, string] => typeof entry[1] === 'string')
  );
}

async function responseBodySnippet(response: Response): Promise<string> {
  const text = (await response.text()).trim();
  return text.length > 600 ? `${text.slice(0, 600)}...` : text;
}

async function requireJsonResponse<T>(response: Response, operation: string): Promise<T> {
  const text = await response.text();
  let payload: unknown;
  try {
    payload = text.trim() ? JSON.parse(text) : undefined;
  } catch {
    throw new Error(
      `${operation} returned non-JSON (${response.status} ${response.statusText}): ${text.slice(0, 600)}`
    );
  }
  if (!response.ok) {
    const apiError = isRecord(payload) && typeof payload.error === 'string' ? payload.error : '';
    throw new Error(
      `${operation} failed (${response.status} ${response.statusText})${apiError ? `: ${apiError}` : ''}`
    );
  }
  return payload as T;
}

function resolveConfig(
  argv: readonly string[] = process.argv.slice(2),
  env: NodeJS.ProcessEnv = process.env
): Config {
  const { values } = parseArgs({
    args: argv,
    options: {
      help: { type: 'boolean', short: 'h', default: false },
      source: { type: 'string' },
    },
    strict: true,
    allowPositionals: false,
  });

  if (values.help) {
    console.log('See the file header for required environment variables and usage.');
    process.exit(0);
  }

  const apiBaseUrl = requiredEnv(env, 'YUCP_API_BASE_URL').replace(/\/+$/, '');
  const parsedApiBaseUrl = new URL(apiBaseUrl);
  if (parsedApiBaseUrl.protocol !== 'http:' && parsedApiBaseUrl.protocol !== 'https:') {
    throw new Error('YUCP_API_BASE_URL must be an HTTP or HTTPS URL.');
  }

  const version = requiredEnv(env, 'YUCP_PACKAGE_VERSION');
  const secondVersion = optionalEnv(env, 'YUCP_SECOND_PACKAGE_VERSION');
  if (secondVersion === version) {
    throw new Error('YUCP_SECOND_PACKAGE_VERSION must differ from YUCP_PACKAGE_VERSION.');
  }

  return {
    apiBaseUrl,
    accessToken: requiredEnv(env, 'YUCP_ACCESS_TOKEN'),
    repoToken: requiredEnv(env, 'YUCP_BACKSTAGE_REPO_TOKEN'),
    catalogProductId: requiredEnv(env, 'YUCP_CATALOG_PRODUCT_ID'),
    packageId: requiredEnv(env, 'YUCP_PACKAGE_ID'),
    version,
    channel: 'stable',
    repositoryVisibility: 'listed',
    releaseStatus: 'published',
    sourcePath: values.source ? resolve(values.source) : undefined,
    secondVersion,
  };
}

function generateSourceZip(packageId: string, version: string): Uint8Array {
  return zipSync(
    {
      'package.json': [
        strToU8(
          JSON.stringify(
            {
              name: packageId,
              version,
              displayName: `Lore live E2E ${packageId}`,
              description: 'Generated by the live Lore Backstage download E2E harness.',
            },
            null,
            2
          )
        ),
        { attrs: 0o644 << 16, level: 9, mtime: FIXED_ZIP_MTIME, os: 3 },
      ],
      'Runtime/lore-e2e.txt': [
        strToU8('Lore Backstage live E2E source\n'),
        { attrs: 0o644 << 16, level: 9, mtime: FIXED_ZIP_MTIME, os: 3 },
      ],
    },
    { level: 9 }
  );
}

async function loadSource(config: Config): Promise<SourceArtifact> {
  if (!config.sourcePath) {
    return {
      bytes: generateSourceZip(config.packageId, config.version),
      contentType: 'application/zip',
      deliveryName: `${config.packageId}-${config.version}.zip`,
    };
  }

  const file = Bun.file(config.sourcePath);
  if (!(await file.exists())) {
    throw new Error(`Source package does not exist: ${config.sourcePath}`);
  }
  const extension = extname(config.sourcePath).toLowerCase();
  if (extension !== '.zip' && extension !== '.unitypackage') {
    throw new Error('--source must point to a .zip or .unitypackage file.');
  }
  return {
    bytes: await file.bytes(),
    contentType: extension === '.zip' ? 'application/zip' : 'application/octet-stream',
    deliveryName: basename(config.sourcePath),
  };
}

function createModifiedZipSource(source: SourceArtifact, secondVersion: string): SourceArtifact {
  if (!source.deliveryName.toLowerCase().endsWith('.zip')) {
    throw new Error('YUCP_SECOND_PACKAGE_VERSION requires a ZIP source artifact.');
  }

  let entries: Record<string, Uint8Array>;
  try {
    entries = unzipSync(source.bytes);
  } catch (error) {
    throw new Error(
      `Could not create the second publish source from the ZIP: ${error instanceof Error ? error.message : String(error)}`
    );
  }

  const modifiedEntries: Zippable = {};
  for (const [path, bytes] of Object.entries(entries)) {
    modifiedEntries[path] = [
      bytes,
      { attrs: 0o644 << 16, level: 9, mtime: FIXED_ZIP_MTIME, os: 3 },
    ];
  }
  modifiedEntries['Runtime/lore-e2e-second-publish.txt'] = [
    strToU8(`Modified source for ${secondVersion}\n`),
    { attrs: 0o644 << 16, level: 9, mtime: FIXED_ZIP_MTIME, os: 3 },
  ];

  return {
    bytes: zipSync(modifiedEntries, { level: 9 }),
    contentType: source.contentType,
    deliveryName: source.deliveryName.replace(/\.zip$/i, `-${secondVersion}.zip`),
  };
}

async function authorizeUpload(
  config: Config,
  source: SourceArtifact,
  version: string
): Promise<UploadAuthorization> {
  const declaredSha256 = sha256Hex(source.bytes);
  const materializeMetadata = {
    ...(config.displayName ? { displayName: config.displayName } : {}),
    ...(isRecord(config.metadata) ? { metadata: config.metadata } : {}),
  };
  const response = await fetch(
    buildApiUrl(
      config.apiBaseUrl,
      `/api/packages/${encodeURIComponent(config.packageId)}/backstage/upload-authorization`
    ),
    {
      method: 'POST',
      signal: AbortSignal.timeout(FETCH_TIMEOUT_MS),
      headers: {
        Authorization: `Bearer ${config.accessToken}`,
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        version,
        deliveryName: source.deliveryName,
        sourceContentType: source.contentType,
        sha256: declaredSha256,
        byteSize: source.bytes.byteLength,
        ...(Object.keys(materializeMetadata).length > 0 ? { materializeMetadata } : {}),
      }),
    }
  );
  const authorization = await requireJsonResponse<UploadAuthorization>(
    response,
    'Backstage upload authorization'
  );
  const tusEndpoint = authorization.tusEndpoint?.trim();
  const uploadToken = authorization.uploadToken?.trim();
  const uploadMetadataKey = authorization.uploadMetadataKey?.trim();
  if (!tusEndpoint || !uploadToken || !uploadMetadataKey) {
    throw new Error('Backstage upload authorization response is missing TUS upload fields.');
  }
  const parsedTusEndpoint = new URL(tusEndpoint);
  if (parsedTusEndpoint.protocol !== 'http:' && parsedTusEndpoint.protocol !== 'https:') {
    throw new Error('Backstage upload authorization returned a non-HTTP TUS endpoint.');
  }
  if (!Number.isSafeInteger(authorization.maxByteSize) || authorization.maxByteSize < 1) {
    throw new Error('Backstage upload authorization returned an invalid maxByteSize.');
  }
  if (source.bytes.byteLength > authorization.maxByteSize) {
    throw new Error(
      `Source exceeds the authorized upload limit. bytes=${source.bytes.byteLength} maxByteSize=${authorization.maxByteSize}`
    );
  }
  return { tusEndpoint, uploadToken, uploadMetadataKey, maxByteSize: authorization.maxByteSize };
}

async function uploadSourceResumably(
  authorization: UploadAuthorization,
  source: SourceArtifact
): Promise<string> {
  const sourceBuffer = Buffer.from(
    source.bytes.buffer,
    source.bytes.byteOffset,
    source.bytes.byteLength
  );
  return await new Promise<string>((resolveUpload, rejectUpload) => {
    let ingestResult: string | undefined;
    const upload = new Upload(sourceBuffer, {
      endpoint: authorization.tusEndpoint,
      metadata: {
        [authorization.uploadMetadataKey]: authorization.uploadToken,
      },
      chunkSize: BACKSTAGE_TUS_CHUNK_SIZE,
      retryDelays: [0, 1000, 3000, 5000],
      removeFingerprintOnSuccess: true,
      onAfterResponse: (_request, response) => {
        const signedResult = response.getHeader(BACKSTAGE_INGEST_RESULT_HEADER)?.trim();
        if (signedResult) {
          ingestResult = signedResult;
        }
      },
      onSuccess: () => {
        if (!ingestResult) {
          rejectUpload(new Error('Backstage ingest sidecar did not return a signed result.'));
          return;
        }
        resolveUpload(ingestResult);
      },
      onError: rejectUpload,
    });
    upload.start();
  });
}

async function publishAuthorizedRelease(
  config: Config,
  ingestResult: string,
  version: string
): Promise<PublishBackstagePackageResult> {
  const response = await fetch(
    buildApiUrl(
      config.apiBaseUrl,
      `/api/packages/${encodeURIComponent(config.packageId)}/backstage/releases`
    ),
    {
      method: 'POST',
      signal: AbortSignal.timeout(FETCH_TIMEOUT_MS),
      headers: {
        Authorization: `Bearer ${config.accessToken}`,
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        catalogProductId: config.catalogProductId,
        ingestResult,
        version,
        ...(config.channel ? { channel: config.channel } : {}),
        ...(config.packageName ? { packageName: config.packageName } : {}),
        ...(config.displayName ? { displayName: config.displayName } : {}),
        ...(config.description ? { description: config.description } : {}),
        ...(config.repositoryVisibility
          ? { repositoryVisibility: config.repositoryVisibility }
          : {}),
        ...(config.defaultChannel ? { defaultChannel: config.defaultChannel } : {}),
        ...(config.unityVersion ? { unityVersion: config.unityVersion } : {}),
        ...(config.metadata !== undefined ? { metadata: config.metadata } : {}),
        ...(config.releaseStatus ? { releaseStatus: config.releaseStatus } : {}),
      }),
    }
  );
  return await requireJsonResponse<PublishBackstagePackageResult>(
    response,
    'Backstage release publish'
  );
}

async function publish(
  config: Config,
  source: SourceArtifact,
  version: string
): Promise<PublishBackstagePackageResult> {
  console.log(
    `[lore-e2e] Uploading ${config.packageId}@${version} (${source.bytes.byteLength} bytes)`
  );
  const authorization = await authorizeUpload(config, source, version);
  const ingestResult = await uploadSourceResumably(authorization, source);
  const result = await publishAuthorizedRelease(config, ingestResult, version);
  if (!/^[0-9a-f]{64}$/.test(result.zipSha256)) {
    throw new Error(`Publish response returned an invalid zipSha256: ${result.zipSha256}`);
  }
  if (result.version !== version) {
    throw new Error(
      `Publish response version mismatch. expected=${version} actual=${result.version}`
    );
  }
  console.log(
    `[lore-e2e] Published release ${result.deliveryPackageReleaseId} with zipSHA256=${result.zipSha256}`
  );
  return result;
}

async function resolveRepositoryManifest(
  config: Config,
  version: string
): Promise<RepositoryManifest> {
  const repositoryUrl = buildApiUrl(config.apiBaseUrl, REPOSITORY_PATH);
  const repositoryResponse = await fetch(repositoryUrl, {
    signal: AbortSignal.timeout(FETCH_TIMEOUT_MS),
    headers: { [REPO_TOKEN_HEADER]: config.repoToken },
  });
  const repository = await requireJsonResponse<Record<string, unknown>>(
    repositoryResponse,
    'VPM repository index request'
  );

  const packages = isRecord(repository.packages) ? repository.packages : undefined;
  const packageEntryValue = packages?.[config.packageId];
  const packageEntry = isRecord(packageEntryValue) ? packageEntryValue : undefined;
  const versions =
    packageEntry && isRecord(packageEntry.versions) ? packageEntry.versions : undefined;
  const manifest = versions && isRecord(versions[version]) ? versions[version] : undefined;
  if (!manifest) {
    const exposedVersions = versions ? Object.keys(versions).sort().join(', ') : '(none)';
    throw new Error(
      `VPM repository did not expose ${config.packageId}@${version}. Exposed versions: ${exposedVersions}`
    );
  }

  const url = typeof manifest.url === 'string' ? manifest.url.trim() : '';
  const zipSha256 =
    typeof manifest.zipSHA256 === 'string' ? manifest.zipSHA256.trim().toLowerCase() : '';
  if (!url) {
    throw new Error(`VPM manifest ${config.packageId}@${version} did not include a download URL.`);
  }
  if (!/^[0-9a-f]{64}$/.test(zipSha256)) {
    throw new Error(`VPM manifest ${config.packageId}@${version} has an invalid zipSHA256.`);
  }

  return {
    headers: {
      [REPO_TOKEN_HEADER]: config.repoToken,
      ...getStringHeaders(manifest.headers),
    },
    url: new URL(url, repositoryUrl).toString(),
    zipSha256,
  };
}

async function downloadThroughRedirect(manifest: RepositoryManifest): Promise<DownloadedArtifact> {
  const packageResponse = await fetch(manifest.url, {
    signal: AbortSignal.timeout(FETCH_TIMEOUT_MS),
    headers: manifest.headers,
    redirect: 'manual',
  });
  if (packageResponse.status !== 302) {
    throw new Error(
      `Package endpoint returned ${packageResponse.status} ${packageResponse.statusText}, expected 302: ${await responseBodySnippet(packageResponse)}`
    );
  }

  const location = packageResponse.headers.get('location')?.trim() ?? '';
  if (!LORE_PRESIGNED_URL_PATTERN.test(location)) {
    throw new Error(
      `Package redirect location was not a Lore presigned URL: ${location || '(missing)'}`
    );
  }

  const downloadResponse = await fetch(location, {
    signal: AbortSignal.timeout(FETCH_TIMEOUT_MS),
    headers: {
      Accept: 'application/zip',
      'Accept-Encoding': 'identity',
    },
    redirect: 'error',
  });
  if (!downloadResponse.ok) {
    throw new Error(
      `Lore presigned download failed (${downloadResponse.status} ${downloadResponse.statusText}): ${await responseBodySnippet(downloadResponse)}`
    );
  }
  const bytes = new Uint8Array(await downloadResponse.arrayBuffer());
  return { bytes, redirectLocation: location, sha256: sha256Hex(bytes) };
}

function assertByteExact(first: Uint8Array, second: Uint8Array): void {
  if (first.byteLength !== second.byteLength) {
    throw new Error(
      `Re-downloaded deliverable length mismatch. first=${first.byteLength} second=${second.byteLength}`
    );
  }
  if (!Buffer.from(first).equals(Buffer.from(second))) {
    throw new Error('Re-downloaded deliverable was not byte-exact.');
  }
}

async function verifyPublishedVersion(
  config: Config,
  version: string,
  published: PublishBackstagePackageResult
): Promise<void> {
  const manifest = await resolveRepositoryManifest(config, version);
  if (manifest.zipSha256 !== published.zipSha256) {
    throw new Error(
      `Published and manifest ZIP digests differ. published=${published.zipSha256} manifest=${manifest.zipSha256}`
    );
  }

  const first = await downloadThroughRedirect(manifest);
  if (first.sha256 !== manifest.zipSha256) {
    throw new Error(
      `Downloaded ZIP digest mismatch. manifest=${manifest.zipSha256} actual=${first.sha256}`
    );
  }

  const secondManifest = await resolveRepositoryManifest(config, version);
  const second = await downloadThroughRedirect(secondManifest);
  if (second.sha256 !== published.zipSha256) {
    throw new Error(
      `Re-downloaded ZIP digest mismatch. published=${published.zipSha256} actual=${second.sha256}`
    );
  }
  assertByteExact(first.bytes, second.bytes);

  console.log(
    `[lore-e2e] Verified ${config.packageId}@${version}: bytes=${first.bytes.byteLength} sha256=${first.sha256}`
  );
}

export async function runLoreBackstageDownloadE2E(config: Config): Promise<void> {
  const source = await loadSource(config);
  const published = await publish(config, source, config.version);
  await verifyPublishedVersion(config, config.version, published);

  if (config.secondVersion) {
    const modifiedSource = createModifiedZipSource(source, config.secondVersion);
    const secondPublished = await publish(config, modifiedSource, config.secondVersion);
    await verifyPublishedVersion(config, config.secondVersion, secondPublished);
  }
}

export async function main(argv: readonly string[] = process.argv.slice(2)): Promise<void> {
  const config = resolveConfig(argv);
  await runLoreBackstageDownloadE2E(config);
  console.log('E2E PASSED');
}

if (import.meta.main) {
  main().catch((error) => {
    const message = error instanceof Error ? error.message : String(error);
    console.error(`E2E FAILED: ${message}`);
    process.exitCode = 1;
  });
}
